server:
  port: 8088

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
        username: root
        password: 052019
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 1
        maxWait: 60000
        maxActive: 20
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        filters: stat
        maxOpenPreparedStatements: 20
        connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 5000
    redis:
        host: 127.0.0.1
        port: 6379
        password: 123
        timeout: 10000
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

    #MVC
    mvc:
      view:
        prefix: classpath:templates
        suffix: /*.html

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql